#
###################################
# Site wide configuration
####################################
#
title: Jackson Osvaldo
email:
description: Um curioso apaixonado por livros, tecnologia e programação.
url: https://jacksonosvaldo.github.io
keywords: ["blog", "Jackson Osvaldo", "Python", "RPA"]
plugins:
  - jekyll-sitemap

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Belem
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jackson Osvaldo
  avatar: avatar.jpeg
  job: "Desenvolvedor Python"
  bio: "Um curioso apaixonado por livros, tecnologia e programação."
  email: jacksonenazus@gmail.com
  disqus-shortname: https-jacksonosvaldo-github-io
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-178775089-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: JacksonOsvaldo
  gitlab: JacksonOsvaldo
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jackson-osvaldo
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: JacksonOsvaldo
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username